# Generated by Django 3.0.7 on 2020-06-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='分类')),
                ('summary', models.CharField(max_length=225, verbose_name='简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category', verbose_name='分类')),
            ],
        ),
    ]
